name: Salesforce Backup

on:
  push:
    branches:
      - master  # Trigger this workflow on a push to the main branch
  schedule:
    - cron: '0 0 * * *'  # Optional: Schedule to run daily at midnight (UTC)

jobs:

  update-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository to the runner
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 2: Make the file updates
      - name: Update Files
        run: |

          curl "https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz" -o "my-sfdx-package.tar.xz"
          tar -xvf my-sfdx-package.tar.xz
          PATH="$PATH:/sf/bin
          echo "${{ secrets.SF_PRIVATE_KEY }}" > ./private.key
          chmod 600 ./private.key
          sf org login jwt --username "${{vars.EMAIL}}" --jwt-key-file "${{secrets.SF_PRIVATE_KEY}}" --client-id "${{vars.CLIENTID}}"

      # Step 3: Commit the changes
      - name: Commit changes
        run: |
          sudo sf project retrieve start --target-org ${{vars.EMAIL}} --manifest package.xml
          sudo git config --global user.name "github-actions[bot]"
          sudo git config --global user.email "github-actions[bot]@users.noreply.github.com"
          sudo git add .
          sudo git commit -m "Automated update files on $(date)" || echo "No changes to commit"

      # Step 4: Push the changes back to the repository
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo git push origin master
      - name: Delete Private Key
        if: always()
        run: |
          sudo rm -f ./private.key
